name: schat_windows
description: A Windows desktop chat application built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  crypto: ^3.0.3
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
